import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-sans bg-gray-50 min-h-screen flex flex-col`}
      >
        {/* Header */}
        <header className="bg-white shadow-md p-4">
          <div className="max-w-7xl mx-auto flex items-center justify-between">
            <h1 className="text-2xl font-bold text-primary">Minha Loja</h1>
            <nav>
              <ul className="flex space-x-4 text-gray-700">
                <li><a href="/" className="hover:text-primary">Home</a></li>
                <li><a href="/produtos" className="hover:text-primary">Produtos</a></li>
                <li><a href="/contato" className="hover:text-primary">Contato</a></li>
              </ul>
            </nav>
          </div>
        </header>

        {/* Main content */}
        <main className="flex-grow max-w-7xl mx-auto p-8 w-full">
          {children}
        </main>

        {/* Footer */}
        <footer className="bg-white shadow-inner p-4 mt-auto text-center text-gray-600 text-sm">
          &copy; {new Date().getFullYear()} Minha Loja. Todos os direitos reservados.
        </footer>
      </body>
    </html>
  );
}
